// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXXqvKNfpDcdTsoiqs15bV6U5HB3YbvE',
    appId: '1:745478017558:web:9e8700f113c47fffcedb37',
    messagingSenderId: '745478017558',
    projectId: 'mob-dev-threes-crowd',
    authDomain: 'mob-dev-threes-crowd.firebaseapp.com',
    storageBucket: 'mob-dev-threes-crowd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkQs0oUWZ5NbynemtzJjE14kdYp1wKy-o',
    appId: '1:745478017558:android:10e7adeb33f6786dcedb37',
    messagingSenderId: '745478017558',
    projectId: 'mob-dev-threes-crowd',
    storageBucket: 'mob-dev-threes-crowd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63wran9ypVk0oTf4vBy6Ut1rwWGdMPW0',
    appId: '1:745478017558:ios:e5feda264724225acedb37',
    messagingSenderId: '745478017558',
    projectId: 'mob-dev-threes-crowd',
    storageBucket: 'mob-dev-threes-crowd.appspot.com',
    iosClientId: '745478017558-i7uvisdckdrj9d0nhf9nfjqtca0abprj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA63wran9ypVk0oTf4vBy6Ut1rwWGdMPW0',
    appId: '1:745478017558:ios:e5feda264724225acedb37',
    messagingSenderId: '745478017558',
    projectId: 'mob-dev-threes-crowd',
    storageBucket: 'mob-dev-threes-crowd.appspot.com',
    iosClientId: '745478017558-i7uvisdckdrj9d0nhf9nfjqtca0abprj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsService',
  );
}
